name = "frontend"
version = "0.1.0"
target = "javascript"

description = "Real-time banking application using Lustre, WebSockets, and eventsourcing_glyn"
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
lustre_websocket = ">= 0.9.0 and < 1.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 1.9.2 and < 2.0.0"
