name = "backend"
version = "0.1.0"

description = "Real-time banking application using Lustre, WebSockets, and plain eventsourcing"
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
mist = ">= 5.0.0 and < 6.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
eventsourcing = ">= 9.0.0 and < 10.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
